name: "Terraform ECS deployment"
 
on:
  workflow_dispatch:
  push:
    branches:
    - main
   
  pull_request:
    branches:
    - main
 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_DEFAULT_REGION: "us-east-2"

jobs:
 terraform:
   name: "Terraform ECS deployment"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: "1.4.2"
   
     - name: Terraform init
       id: init
       run: terraform init
   
     - name: Terraform validate
       id: validate
       run: terraform validate
 
     - name: Terraform plan
       id: plan
       run: terraform plan
       continue-on-error: true
 
     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1
 
     - name: Terraform Apply
       id: apply
       run: terraform apply --auto-approve
